### ISSUE TITLE
how to use the simulator

### ISSUE THREAD

**Issue by solrac57** [WChargin/lc3web#10]
Is there any reference to how to use the simulator? e.g. does it work just like the Linux one?
thx

**Comment by wchargin** [comment]
You can use the simulator online: <https://wchargin.github.io/lc3web/>

There are three panes: “Memory”, “Status”, and “Console”.

The **Memory** pane lets you inspect and modify the full memory of the
simulated LC-3. At the bottom of the Memory pane, you’ll see two
buttons: “Assemble” and “Raw”. Clicking the “Assemble” button will let
you input a program as LC-3 assembly source code. Clicking the “Raw”
button will let you input a program as already-assembled machine code
(as hex or binary). To the left of the “Assemble” and “Raw” buttons is
an upload button to facilitate uploading object files and symbol tables
from disk.

The **Status** pane lets you inspect and modify the LC-3 state. The
eight general-purpose registers, plus the program counter, instruction
register, and program status register are all displayed and editable.
The condition codes are also displayed (but not editable, because they
are computed from the PSR value). Below the registers you’ll see the
standard buttons for managing the execution (run, step, pause, etc.).

The **Console** pane handles I/O. Characters are written to the large
text box as the LC-3 execution progresses. You can click in the text box
and type in it to provide input to the LC-3.

Is there anything else that you’d like to know?

**Comment by wchargin** [comment]
Closing this question as answered. Feel free to comment if you have
outstanding questions.
