### ISSUE TITLE
Support for laser style symbol files

### ISSUE THREAD

**Issue by nstringham** [WChargin/lc3web#12]
consider the following lc3 assembly
```
.ORIG	x3000
	myLable HALT
.END
```
lc3web would create a symbol files that looks like this
```
// Symbol table
// Symbol Name       Page Address
// ----------------  ------------
// myLable           3000
```
[laser](https://github.com/PaperFanz/laser) would create a symbol file like this
```
myLable                                                                    x3000
```
when you upload a symbol file to lc3web using the upload file feature it will only work if it is in the format output by lc3web.

I would like lc3web to also support uploading laser style symbol files

**Comment by wchargin** [comment]
Hi @nstringham! Thanks for the suggestion. Done.

While I don't really feel obligated to support every other format under
the sun (the format that lc3web uses is the one used by the standard set
of tools, to the best of my knowledge), the change to accommodate your
example file is easy enough, so I've implemented and pushed it. Let me
know if this works for you.

(FWIW, the example symbol file that you generate seems a bit confusing
to me. It shows up like this:

![Screenshot of the example symbol file, showing only the word `myLable` because a horizontal scrollbar hides the actual label value.][ss]

…and it was not obvious to me that there was actually a label value to
the right after 68 consecutive spaces.)

[ss]: https://user-images.githubusercontent.com/4317806/142295911-cb6c9e22-5ebb-4001-a959-78d6f2d87df4.png

**Comment by nstringham** [comment]
> (FWIW, the example symbol file that you generate seems a bit confusing to me. It shows up like this:
> 
> …and it was not obvious to me that there was actually a label value to the right after 68 consecutive spaces.)

Yeah I'm not sure why they add so many spaces. Presumably it's so that they don't have to deal with long label names.

**Comment by nstringham** [comment]
thanks! I have tested and it seams to be working as excepted 👍
