### ISSUE TITLE
OUT/PUTS display printing speed much slower in Safari

### ISSUE THREAD

**Issue by hawkfalcon** [WChargin/lc3web#2]
Another very minor bug, sorry to disturb you again,

In Safari, if you output to console w/ PUTS or OUT or manually with a device register, it is much slower than with chrome. 

![output speed](https://cloud.githubusercontent.com/assets/1509618/10703403/d69d10d2-7984-11e5-9932-fedcdbc066d1.gif)

This is a gif to show what I mean by output speed. The actual assembly doesn't vary.

**Comment by hawkfalcon** [comment]
The gif is chrome, safari is way slower by comparison.

**Comment by wchargin** [comment]
Interesting. I don't have a local copy of Safari to test, but it [looks okay to me](http://gfycat.com/CrispFaintKarakul) via BrowserStack:
[![GIF (click for gfycat) of decently fast output](http://fat.gfycat.com/CrispFaintKarakul.gif)](http://gfycat.com/CrispFaintKarakul)

Is it possible that Safari's JS runtime is just slower than Chrome's?

It's worth noting that the text is intentionally slowed down. Because of the nature of the polling (in case you haven't covered this yet: you write an ASCII char to a specific register, then just loop forever until the LC-3 magically writes that character and changes another register to let you know), the JS would cause the page to hang if you're waiting for user input.

That is, if the JavaScript keeps spinning and waiting for you to press a key, you won't be able to press a key because the browser won't be able to process your input while the JS is running.

This is handled [here](https://github.com/wchargin/lc3web/blob/gh-pages/js/lc3_ui.js#L299-L336), so if there actually is a difference on my end then that's probably where it is.

But I will say that I only test things in Chrome, because Firefox is also really compliant and I expect that most devs use one of those two browsers. Feel free to report Safari issues, but unless you have a fix—especially with performance issues where non-local testing doesn't make as much sense—there's not too much I can do.

Oh, and don't worry about disturbing me! If I have other things to do, I'll do them and see this eventually! :smile: The point of the issues system is exactly to facilitate asynchronous interactions like this.

**Comment by wchargin** [comment]
Closing because I haven't seen any evidence that the performance issue is on my end, and I don't have any obvious ideas to speed up Safari.

**Comment by wchargin** [comment]
@hawkfalcon if you're still interested, I think I've identified a major performance boost, which I will try out in the new version and _maybe_ merge early…I'll keep you apprised if you like.

(**Edit for posterity:** This comment referred to a "batch mode" functionality in which we don't perform DOM updates while executing a sequence of commands. I never got around to polishing it, but if you like you can take a look at https://github.com/wchargin/lc3/commits/batch.)
