### ISSUE TITLE
BR does not assemble on CENTOS6 Firefox or chrome

### ISSUE THREAD

**Issue by jplanck** [WChargin/lc3web#4]
When assembling a program with BRx on CENTOS running firefox or chrome, one of the following error messages occur.  This works on Windows firefox and chrome.

Oh no! You've got an error in your assembly code:
    at line 24: upname.substring(...).includes is not a function

Chrome:
Oh no! You've got an error in your assembly code:
    Object [object Array] has no method 'findIndex'

I can privately email my testfile  if necessary.

**Comment by wchargin** [comment]
Got it—I'll add a polyfill. (I have one for `Array.prototype.includes` already, but forgot that this isn't Haskell and `String`s aren't just `[Char]`s! :smile:)

By the way, the [`includes` function is ES6](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes), supported since Firefox 40 (August 2015) and Chrome 41 (March 2015)…so those lab machines are missing a bunch of more important security updates as well! I've also had issues with those machines having really out-of-date versions of `bash` (no `declare -A`), `gcc` (no `-Og`), and `git` (forget what). So what can you do…

**Comment by wchargin** [comment]
I'd like to say this is fixed by ebe072e23fb6c2cafb4db216bc8f2bd80467992d, but I can't test it. @jplanck, could you give it a shot at your convenience?

**Comment by wchargin** [comment]
(will reopen if someone confirms this is still broken)
