### ISSUE TITLE
Trap x23 does not issue prompt.

### ISSUE THREAD

**Issue by jplanck** [WChargin/lc3web#5]
Trap x23 IN is defined:
Print a prompt on the screen and read a single character from the keyboard. The character is echoed onto the console monitor, and its ASCII code is copied into R0. The high eight bits of R0 are cleared.

The prompt on windows and unix is:
Input a character>

There is no prompt on the web version.

This is making it difficult to explain the difference between IN and GETC

**Comment by wchargin** [comment]
Oh! I see. I will add this.

There still is a difference between `IN` and `GETC`, though, in that `GETC` does not echo the character, correct?

**Comment by wchargin** [comment]
I'll try to do this tomorrow. It should not be difficult, because it's an issue with the preloaded OS, not with the assembler core or UI.

If you want to try it yourself in the meantime, the relevant file is [`lc3_os.js`](https://github.com/WChargin/lc3web/blob/gh-pages/js/lc3_os.js). You can either modify the `IN` trap yourself or just copy the raw instructions from the Windows/Unix simulator's preloaded memory (after verifying, of course, that this is permitted by the license).

**Comment by jplanck** [comment]
Correct, Getc does not echo the character.

**Comment by wchargin** [comment]
Okay. I don't see why the current subroutine is so long. It looks like this should do the trick:

``` asm
        .ORIG x04A0

TRAP_IN
        ST      R7, SaveR7
        LEA     R0, Message
        PUTS
        GETC
        OUT
        LD      R7, SaveR7
        RET

SaveR7  .BLKW   #1
Message .STRINGZ "Input a character> "

        .END
```

Does this seem right to you? If I missed something, let me know and I'll change it. But it seems to meet the spec.

**Comment by jplanck** [comment]
verified.

thanks.

john
